import type { Metadata } from 'next'
import { Inter, Oswald } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

const oswald = Oswald({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Gabyto Electronics',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={oswald.className}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	)
}
